# Generated by Django 4.1.7 on 2023-07-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TimelineStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(max_length=2500)),
                ("dragon_title", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("publish_date", models.DateTimeField(auto_now_add=True)),
                ("image1", models.ImageField(upload_to="travel_pics")),
                ("image2", models.ImageField(upload_to="travel_pics")),
            ],
        ),
    ]
