# Generated by Django 4.1.7 on 2023-07-19 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
        ("timemachine", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timelinestory",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_author",
                to="login.userprofile",
            ),
        ),
    ]
